config/routes.rb
Rails.application.routes.draw do
  post 'like/:post_id' => 'likes#create', as: 'like'
  post 'dislike/:post_id' => 'likes#destroy', as: 'dislike'
  root 'posts#index'
  devise_for :users
  resources :user, only: :show
  resources :posts, only: [:create, :new]
  resources :comments , only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	validates :body, presence: true,
                    length: { minimum: 1, maximum: 250 }

  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

	validates :title, presence: true,
                    length: { minimum: 1, maximum: 250 }

  validate :correct_image_type

  belongs_to :user
  has_many_attached :images
  has_many :comments
  has_many :likes 


  private 

  def correct_image_type

  	if images.attached? && !images.all? {|image| image.content_type.in?( %w( image/jpeg image/png )) }
      errors.add(:images , 'Must be a JPEG or a PNG')
  	elsif images.attached? == false 
  		errors.add(:images , 'required')
  	end

  end

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true, length: { maximum: 50 }

has_many :posts
has_many :comments
has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new 
		
	end

	def create 
		comment = Comment.new(comment_params)
		comment.user = current_user

		comment.save


		redirect_to user_path(comment.user)
	end

	private 

	def comment_params
    params.require(:comment).permit(:post_id, :body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		# like = Like.new
		# like.user_id = current_user.id
		# like.post_id = params[:post_id]
		# like.save

		user = current_user
		post = Post.find(params[:post_id])

		like = Like.find_by( user_id: user.id, post_id: post.id )

		if like == nil 
			like = Like.new(user_id: current_user.id, post_id: post.id)
			like.save
		end

		redirect_to user_path(like.user)
	end 

	def destroy
		post = Post.find(params[:post_id])
		like = Like.find_by( user_id: current_user.id, post_id: post.id )
		like.destroy
	    redirect_to user_path(like.user)
	end 


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

  def destroy

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save 
      redirect_to user_path(@post.user)
    else
      render 'new'
    end
  end

  def index
  end

  private

  def post_params
    params.require(:post).permit(:title, :user_id, images: [])
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
 	@user = User.find(params[:id])
	@posts = @user.posts.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def is_already_liked?(post)
		if Like.find_by( user_id: current_user.id, post_id: post.id ) == nil 
			false
		else 
			true
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_form.html.erb
<%= form_with scope: :comment, url: comments_path, local: true do |f| %>
	 <%= f.text_area :body, class: 'form-group' %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.submit class: 'btn btn-secondary' %>
    
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      &#x2630;
    </button>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="navbar-nav ml-auto">
        <div class="navbar-nav ml-auto">
          <% if user_signed_in? %>
  <div class="nav-item">
    <span class="navbar-text">
      Hello, &nbsp;
    <span>
  </div>

  <div class="dropdown show">
    <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
    </div>
  <div>

           <% else %>
              <div class="nav-item">
               <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
             </div>
             <div class="nav-item">
               <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
             </div>
          <% end %>
        </div>
      </div>
    </div>
 </div>
</nav>


<br>
<br>
<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/navbar' %> 

    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
 <% if @post.errors.any? %>
        <div class="errors">
          Total errors: <%= @post.errors.count %>
          <ul>
            <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

<% if current_user  %>
	<%= form_with url: posts_path, scope: :post, local: true do |f| %>
		<%= f.text_field :title %>
		<%= f.file_field :images, multiple: true %>
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.submit %> 
	<% end %>
<% end %>

app/views/posts/show.html.erb
<%= user.title %>
<%= image_tag user.image if user.image.attached?%> 

app/views/user/show.html.erb
<% @posts.each do |post| %> 
<div class="container" style=" max-width: 400px">
<div class="card" style="margin-bottom: 20px; padding: 10px">
  <div class="card-body">
    <h2> @<%= post.user.name %> </h2>
    <h5 class="card-title"> <%= post.title %> </h5>
    <p class="card-text"><small class="text-muted"> <%= post.created_at %></small></p>
  </div>
  
<% if post.images.attached? %> 
  <% post.images.each do |image| %>
  <div>	<%= image_tag image, style: 'width: 340px' %> </div>
  <% end %> 
<% end %>

  <% post.comments.each do |comment| %>
  <%= comment.user.name %> 
    <p class="card-text"> <%= comment.body %> </p>

  <% end %>
<% if is_already_liked?(post) %>  
     <%= link_to dislike_path(post), method: :post do %>
            <i class="fa fa-heart" aria-hidden="true"></i>
     <% end %>
<% else %> 
   <%= link_to like_path(post), method: :post do %>
          <i class="fa fa-heart-o" aria-hidden="true"></i>
   <% end %>  
<% end %> 
 <%= render 'comments/form', post: post %> 
</div>
</div>
<% end %> 